# Generated by Django 2.2.20 on 2021-05-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.TextField(blank=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=256, null=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('o2level', models.IntegerField(blank=True, null=True)),
                ('doctor', models.TextField(blank=True, null=True)),
                ('problemsice', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
